### ISSUE TITLE
updating toml

### ISSUE THREAD

**Issue by lucadimascolo** [thomaswmorris/maria#49]
Just a minor issue.
After installing `maria` in a fresh `conda` environment (with python 3.10), I had to install manually the `requests` package (https://pypi.org/project/requests/) and to force `numpy` to upgrade to a version `>=1.22.4` (due to some conflicts with `pandas`).

I am noting this here for the record, but I guess it might be good to include this in the `toml` file.

**Comment by thomaswmorris** [comment]
Good point
